import React from "react";

import styles from "./Privacy.module.scss";

export default () => {
  return (
    <div className={styles.container}>
      <h1>Privacy Policy</h1>
      <br />

      <h3>
        Alexi Christakis built the Paint Party app as a Free app. This service
        is provided by Alexi Christakis at no cost and is intended for use as
        is.
      </h3>
      <br />
      <h3>
        This page is used to inform visitors regarding my policies with the
        collection, use, and disclosure of Personal Information if anyone
        decided to use my Service.
      </h3>
      <br />
      <h3>
        If you choose to use my Service, then you agree to the collection and
        use of information in relation to this policy. The Personal Information
        that I collect is used for providing and improving the Service. I will
        not use or share your information with anyone except as described in
        this Privacy Policy.
      </h3>
      <br />
      <h3>
        The terms used in this Privacy Policy have the same meanings as in our
        Terms and Conditions, which is accessible at Paint Party unless
        otherwise defined in this Privacy Policy.
      </h3>
      <br />

      <h2>Information Collection and Use</h2>

      <h3>
        For a better experience, while using our Service, I may require you to
        provide us with certain personally identifiable information, including
        but not limited to device OS, phone number. The information that I
        request will be retained on your device and is not collected by me in
        any way.
      </h3>
      <br />

      <h2>Log Data</h2>
      <h3>
        I want to inform you that whenever you use my Service, in a case of an
        error in the app I collect data and information (through third party
        products) on your phone called Log Data. This Log Data may include
        information such as your device Internet Protocol (“IP”) address, device
        name, operating system version, the configuration of the app when
        utilizing my Service, the time and date of your use of the Service, and
        other statistics.
      </h3>
      <br />

      <h2>Cookies</h2>

      <h3>
        Cookies are files with a small amount of data that are commonly used as
        anonymous unique identifiers. These are sent to your browser from the
        websites that you visit and are stored on your device's internal memory.
      </h3>
      <br />
      <h3>
        This Service does not use these “cookies” explicitly. However, the app
        may use third party code and libraries that use “cookies” to collect
        information and improve their services. You have the option to either
        accept or refuse these cookies and know when a cookie is being sent to
        your device. If you choose to refuse our cookies, you may not be able to
        use some portions of this Service.
      </h3>
      <br />

      <h2>Security</h2>
      <h3>
        I value your trust in providing us your Personal Information, thus we
        are striving to use commercially acceptable means of protecting it. But
        remember that no method of transmission over the internet, or method of
        electronic storage is 100% secure and reliable, and I cannot guarantee
        its absolute security.
      </h3>
      <br />

      <h2>Children’s Privacy</h2>
      <h3>
        These Services do not address anyone under the age of 13. I do not
        knowingly collect personally identifiable information from children
        under 13. In the case I discover that a child under 13 has provided me
        with personal information, I immediately delete this from our servers.
        If you are a parent or guardian and you are aware that your child has
        provided us with personal information, please contact me so that I will
        be able to do necessary actions.
      </h3>
      <br />

      <h2>Changes to This Privacy Policy</h2>

      <h3>
        I may update our Privacy Policy from time to time. Thus, you are advised
        to review this page periodically for any changes. I will notify you of
        any changes by posting the new Privacy Policy on this page.
      </h3>
      <br />
      <h3>This policy is effective as of 2020-05-05</h3>
      <br />

      <h2>Contact Us</h2>
      <h3>
        If you have any questions or suggestions about my Privacy Policy, do not
        hesitate to contact me at alexi.christakis@gmail.com.
      </h3>
      <br />
      <p>
        This privacy policy page was created at privacypolicytemplate.net and
        modified/generated by App Privacy Policy Generator
      </p>
      <br />
    </div>
  );
};
